_target_: algos.DQN
network_type: Default
network_config:
  Q_network:
    hidden_units: [120, 84]
eps_initial: 0.1
eps_final: 0.05
decay_fraction: 0.5
gamma: 0.99
batch_size: 256
buffer_size: 100000
learning_rate: 0.00025
optimizer: Adam
optimizer_kwargs: {}
anneal_lr: false
target_copy_freq: 10
training_start: ${trainer.training_start}
max_step: ${trainer.max_step}
device: cpu
