_target_: diverserl.algos.SAC
network_type: Default
network_config:
  Actor:
    hidden_units: [256, 256]
  Critic:
    hidden_units: [256, 256]
gamma: 0.99
alpha: 0.1
train_alpha: true
target_alpha: null
tau: 0.005
target_critic_update: 2
batch_size: 256
buffer_size: 1000000
actor_lr: 0.0003
actor_optimizer: Adam
actor_optimizer_kwargs: {}
critic_lr: 0.001
critic_optimizer: Adam
critic_optimizer_kwargs: {}
alpha_lr: 0.001
alpha_optimizer: Adam
alpha_optimizer_kwargs: {}
device: cpu
