[tool.poetry]
name = "diverserl"
version = "0.0.1"
description = "Diverse deep Reinforcement Learning algorithms that can be applied to wide variety of environments"
authors = ["Yoonhee Gil <moripiri1234@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.10.13,<3.13"
torch = "^2.1.0"
jax = {extras = ["cpu"], version = "^0.4.18"}

gymnasium = {version="^0.29.1", extras = ['all']}
AutoROM = {version = ">=0.4.2,<0.5.0", extras = ["accept-rom-license"]}

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
