[tool.poetry]
name = "diverserl"
version = "0.0.1"
description = "Diverse deep Reinforcement Learning algorithms that can be applied to wide variety of environments"
authors = ["Yoonhee Gil <moripiri1234@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "3.10.13"
torch = "^2.1.0"
torchvision = "^0.16.0"
torchaudio = "^2.1.0"
gymnasium = {extras = ["accept-rom-license"], version = "^0.29.1"}
mujoco = "^2.3.7"
swig = "^4.1.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
