_target_: diverserl.trainers.deeprl_trainer.DeepRLTrainer
seed: 1
training_start: 0
training_freq: ${algo.horizon}
training_num: 1
max_step: 2000000
do_eval: true
eval_every: 10000
eval_ep: 1
record: ${env.record}
log_tensorboard: false
log_wandb: false
save_model: false
save_freq: 100000
