_target_: diverserl.trainers.SequenceOfflineTrainer
seed: 1
max_step: 100000
do_eval: true
eval_every: 100
eval_ep: 1
log_tensorboard: false
log_wandb: false
record: ${env.record}
save_model: false
save_freq: 100000
