_target_: diverserl.common.make_env.make_envs
env_id: dm_control/cartpole-swingup-v0
env_option:
  render_mode: rgb_array
  render_kwargs:
    width: 84
    height: 84
wrapper_option:
  FrameSkipWrapper:
    frame_skip: 8
  FlattenObservation: {}
  AddRenderObservation: {}
  GrayscaleObservation: {}
  FrameStackObservation:
    stack_size: 3
seed: ${trainer.seed}
num_envs: 1
vector_env: true
render: false
record: false
