_target_: diverserl.common.make_env.make_envs
env_id: ALE/Pong-v5
env_option:
    repeat_action_probability: 0.
    frameskip: 1 # had to be fixed as 1 for ataripreprocessing
wrapper_option:
  AtariPreprocessing:
    frame_skip: 4
    screen_size: 84
    noop_max: 30
    terminal_on_life_loss: True
    grayscale_obs: True
    scale_obs: False # Observation is scaled at encoder.
  FrameStackObservation:
    stack_size: 4

seed: ${trainer.seed}
num_envs: 1
vector_env: true
render: false
record: false
