_target_: diverserl.common.make_offline_env.make_offline_envs
dataset_id: mujoco/ant/expert-v0
filter_option: {}
eval_env_option: {}
eval_wrapper_option: {}
seed: ${trainer.seed}
vector_env: true
render: false
record: false
