# env setting
env_id: MountainCar-v0
render: false
env_option: {}

# dqn setting
network_type: Default
network_config:
  Q_network:
    hidden_units: [120, 84]
eps_initial: 0.1
eps_final: 0.05
decay_fraction: 0.5
gamma: 0.99
batch_size: 128
buffer_size: 100000
learning_rate: 0.00025
optimizer: Adam
optimizer_kwargs: {}
target_copy_freq: 10
device: cpu

# trainer setting
seed: 4
training_start: 10000
training_freq: 1
training_num: 1
max_step: 200000
do_eval: true
eval_every: 10000
eval_ep: 1

# log setting
log_tensorboard: true
log_wandb: true
record_video: true
save_model: false
save_freq: 100000
