defaults:
  - env: minari_mujoco
  - algo: offline_rl/bc
  - trainer: offline_trainer

env:
  dataset_id: mujoco/ant/expert-v0
  filter_option:
    filter_reward:
      dataset_frac: ${algo.dataset_frac}
      gamma: ${algo.gamma}
    normalize_dataset: {}

hydra:
  run:
    dir: .
  output_subdir: null
