defaults:
  - env: minari_mujoco
  - algo: offline_rl/dt
  - trainer: sequence_offline_trainer

env:
  dataset_id: mujoco/ant/expert-v0
  filter_option:
    normalize_observation: {}
    scale_reward:
      scale: 0.001
  buffer_name: SequenceDatasetBuffer

hydra:
  run:
    dir: .
  output_subdir: null
