_target_: diverserl.algos.pixel_rl.SAC_AE
network_type: Default
network_config:
  Actor:
    hidden_units:
      - 256
      - 256
  Critic:
    hidden_units:
      - 256
      - 256
  Encoder:
    feature_dim: 50
    layer_num: 4
    channel_num:
      - 32
      - 32
      - 32
      - 32
    kernel_size:
      - 3
      - 3
      - 3
      - 3
    strides:
      - 2
      - 1
      - 1
      - 1
    last_activation: Tanh
    layer_norm: true
  Decoder:
    layer_num: 4
    channel_num:
      - 32
      - 32
      - 32
      - 32
    kernel_size:
      - 3
      - 3
      - 3
      - 3
    strides:
      - 1
      - 1
      - 1
      - 2
  Buffer:
    optimize_memory_usage: true
gamma: 0.99
alpha: 0.1
train_alpha: true
target_alpha: null
tau: 0.01
target_critic_update: 2
batch_size: 128
buffer_size: 100000
decoder_latent_lambda: 1e-5
decoder_weight_lambda: 1e-6

actor_lr: 0.001
actor_optimizer: Adam
actor_optimizer_kwargs: {}
critic_lr: 0.001
critic_optimizer: Adam
critic_optimizer_kwargs: {}
alpha_lr: 0.0001
alpha_optimizer: Adam
alpha_optimizer_kwargs:
  betas: (0.5, 0.999)
encoder_lr: 0.001
encoder_optimizer: Adam
encoder_optimizer_kwargs: {}
decoder_lr: 0.001
decoder_optimizer: AdamW
decoder_optimizer_kwargs: {}

device: cpu
