env_id: BipedalWalker-v3
render: false
env_option: {}

network_type: Default
network_config:
  Actor: {}
  Critic: {}
gamma: 0.99
alpha: 0.1
train_alpha: true
target_alpha: null
tau: 0.05
critic_update: 2
batch_size: 256
buffer_size: 1000000
actor_lr: 0.001
actor_optimizer: Adam
actor_optimizer_kwargs: {}
critic_lr: 0.001
critic_optimizer: Adam
critic_optimizer_kwargs: {}
alpha_lr: 0.001
alpha_optimizer: Adam
alpha_optimizer_kwargs: {}
device: cpu
seed: 1

training_start: 1000
training_freq: 1
training_num: 1
train_type: online
max_step: 100000
do_eval: true
eval_every: 10000
eval_ep: 10
log_tensorboard: false
log_wandb: false
save_model: false
save_freq: 100000
